# Generated by Django 2.1 on 2019-03-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190302_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='movies_by_category', to='webapp.Category', verbose_name='Категория фильма'),
        ),
    ]
