# Generated by Django 2.1 on 2019-03-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20190306_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='seat',
            new_name='place',
        ),
    ]
