# Generated by Django 2.1 on 2019-03-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_discount_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='code',
        ),
    ]
