# Generated by Django 2.1.7 on 2019-03-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_book_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.CharField(default='835016', editable=False, max_length=10, unique_for_date='created_at', verbose_name='Код брони'),
        ),
    ]
