# Generated by Django 2.1.7 on 2019-03-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20190330_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.CharField(default='629151', editable=False, max_length=10, unique_for_date='created_at', verbose_name='Код брони'),
        ),
    ]
